// Generated by gencpp from file roboteq_motor_controller_driver/channel_values.msg
// DO NOT EDIT!


#ifndef ROBOTEQ_MOTOR_CONTROLLER_DRIVER_MESSAGE_CHANNEL_VALUES_H
#define ROBOTEQ_MOTOR_CONTROLLER_DRIVER_MESSAGE_CHANNEL_VALUES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roboteq_motor_controller_driver
{
template <class ContainerAllocator>
struct channel_values_
{
  typedef channel_values_<ContainerAllocator> Type;

  channel_values_()
    : value()  {
    }
  channel_values_(const ContainerAllocator& _alloc)
    : value(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int64_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int64_t>> _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::roboteq_motor_controller_driver::channel_values_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboteq_motor_controller_driver::channel_values_<ContainerAllocator> const> ConstPtr;

}; // struct channel_values_

typedef ::roboteq_motor_controller_driver::channel_values_<std::allocator<void> > channel_values;

typedef boost::shared_ptr< ::roboteq_motor_controller_driver::channel_values > channel_valuesPtr;
typedef boost::shared_ptr< ::roboteq_motor_controller_driver::channel_values const> channel_valuesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboteq_motor_controller_driver::channel_values_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboteq_motor_controller_driver::channel_values_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roboteq_motor_controller_driver::channel_values_<ContainerAllocator1> & lhs, const ::roboteq_motor_controller_driver::channel_values_<ContainerAllocator2> & rhs)
{
  return lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roboteq_motor_controller_driver::channel_values_<ContainerAllocator1> & lhs, const ::roboteq_motor_controller_driver::channel_values_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roboteq_motor_controller_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::roboteq_motor_controller_driver::channel_values_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboteq_motor_controller_driver::channel_values_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboteq_motor_controller_driver::channel_values_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboteq_motor_controller_driver::channel_values_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboteq_motor_controller_driver::channel_values_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboteq_motor_controller_driver::channel_values_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboteq_motor_controller_driver::channel_values_<ContainerAllocator> >
{
  static const char* value()
  {
    return "67631b021b5d5374cfd8a5bd8b56428a";
  }

  static const char* value(const ::roboteq_motor_controller_driver::channel_values_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x67631b021b5d5374ULL;
  static const uint64_t static_value2 = 0xcfd8a5bd8b56428aULL;
};

template<class ContainerAllocator>
struct DataType< ::roboteq_motor_controller_driver::channel_values_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboteq_motor_controller_driver/channel_values";
  }

  static const char* value(const ::roboteq_motor_controller_driver::channel_values_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboteq_motor_controller_driver::channel_values_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64[] value\n"
;
  }

  static const char* value(const ::roboteq_motor_controller_driver::channel_values_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboteq_motor_controller_driver::channel_values_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct channel_values_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboteq_motor_controller_driver::channel_values_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboteq_motor_controller_driver::channel_values_<ContainerAllocator>& v)
  {
    s << indent << "value[]" << std::endl;
    for (size_t i = 0; i < v.value.size(); ++i)
    {
      s << indent << "  value[" << i << "]: ";
      Printer<int64_t>::stream(s, indent + "  ", v.value[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTEQ_MOTOR_CONTROLLER_DRIVER_MESSAGE_CHANNEL_VALUES_H
