// Generated by gencpp from file roboteq_motor_controller_driver/command_srv.msg
// DO NOT EDIT!


#ifndef ROBOTEQ_MOTOR_CONTROLLER_DRIVER_MESSAGE_COMMAND_SRV_H
#define ROBOTEQ_MOTOR_CONTROLLER_DRIVER_MESSAGE_COMMAND_SRV_H

#include <ros/service_traits.h>


#include <roboteq_motor_controller_driver/command_srvRequest.h>
#include <roboteq_motor_controller_driver/command_srvResponse.h>


namespace roboteq_motor_controller_driver
{

struct command_srv
{

typedef command_srvRequest Request;
typedef command_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct command_srv
} // namespace roboteq_motor_controller_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roboteq_motor_controller_driver::command_srv > {
  static const char* value()
  {
    return "c6a1a0e621254ff7bba438d5bd95fa58";
  }

  static const char* value(const ::roboteq_motor_controller_driver::command_srv&) { return value(); }
};

template<>
struct DataType< ::roboteq_motor_controller_driver::command_srv > {
  static const char* value()
  {
    return "roboteq_motor_controller_driver/command_srv";
  }

  static const char* value(const ::roboteq_motor_controller_driver::command_srv&) { return value(); }
};


// service_traits::MD5Sum< ::roboteq_motor_controller_driver::command_srvRequest> should match
// service_traits::MD5Sum< ::roboteq_motor_controller_driver::command_srv >
template<>
struct MD5Sum< ::roboteq_motor_controller_driver::command_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roboteq_motor_controller_driver::command_srv >::value();
  }
  static const char* value(const ::roboteq_motor_controller_driver::command_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roboteq_motor_controller_driver::command_srvRequest> should match
// service_traits::DataType< ::roboteq_motor_controller_driver::command_srv >
template<>
struct DataType< ::roboteq_motor_controller_driver::command_srvRequest>
{
  static const char* value()
  {
    return DataType< ::roboteq_motor_controller_driver::command_srv >::value();
  }
  static const char* value(const ::roboteq_motor_controller_driver::command_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roboteq_motor_controller_driver::command_srvResponse> should match
// service_traits::MD5Sum< ::roboteq_motor_controller_driver::command_srv >
template<>
struct MD5Sum< ::roboteq_motor_controller_driver::command_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roboteq_motor_controller_driver::command_srv >::value();
  }
  static const char* value(const ::roboteq_motor_controller_driver::command_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roboteq_motor_controller_driver::command_srvResponse> should match
// service_traits::DataType< ::roboteq_motor_controller_driver::command_srv >
template<>
struct DataType< ::roboteq_motor_controller_driver::command_srvResponse>
{
  static const char* value()
  {
    return DataType< ::roboteq_motor_controller_driver::command_srv >::value();
  }
  static const char* value(const ::roboteq_motor_controller_driver::command_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTEQ_MOTOR_CONTROLLER_DRIVER_MESSAGE_COMMAND_SRV_H
