// Generated by gencpp from file roboteq_motor_controller_driver/config_srv.msg
// DO NOT EDIT!


#ifndef ROBOTEQ_MOTOR_CONTROLLER_DRIVER_MESSAGE_CONFIG_SRV_H
#define ROBOTEQ_MOTOR_CONTROLLER_DRIVER_MESSAGE_CONFIG_SRV_H

#include <ros/service_traits.h>


#include <roboteq_motor_controller_driver/config_srvRequest.h>
#include <roboteq_motor_controller_driver/config_srvResponse.h>


namespace roboteq_motor_controller_driver
{

struct config_srv
{

typedef config_srvRequest Request;
typedef config_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct config_srv
} // namespace roboteq_motor_controller_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roboteq_motor_controller_driver::config_srv > {
  static const char* value()
  {
    return "c6a1a0e621254ff7bba438d5bd95fa58";
  }

  static const char* value(const ::roboteq_motor_controller_driver::config_srv&) { return value(); }
};

template<>
struct DataType< ::roboteq_motor_controller_driver::config_srv > {
  static const char* value()
  {
    return "roboteq_motor_controller_driver/config_srv";
  }

  static const char* value(const ::roboteq_motor_controller_driver::config_srv&) { return value(); }
};


// service_traits::MD5Sum< ::roboteq_motor_controller_driver::config_srvRequest> should match
// service_traits::MD5Sum< ::roboteq_motor_controller_driver::config_srv >
template<>
struct MD5Sum< ::roboteq_motor_controller_driver::config_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roboteq_motor_controller_driver::config_srv >::value();
  }
  static const char* value(const ::roboteq_motor_controller_driver::config_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roboteq_motor_controller_driver::config_srvRequest> should match
// service_traits::DataType< ::roboteq_motor_controller_driver::config_srv >
template<>
struct DataType< ::roboteq_motor_controller_driver::config_srvRequest>
{
  static const char* value()
  {
    return DataType< ::roboteq_motor_controller_driver::config_srv >::value();
  }
  static const char* value(const ::roboteq_motor_controller_driver::config_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roboteq_motor_controller_driver::config_srvResponse> should match
// service_traits::MD5Sum< ::roboteq_motor_controller_driver::config_srv >
template<>
struct MD5Sum< ::roboteq_motor_controller_driver::config_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roboteq_motor_controller_driver::config_srv >::value();
  }
  static const char* value(const ::roboteq_motor_controller_driver::config_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roboteq_motor_controller_driver::config_srvResponse> should match
// service_traits::DataType< ::roboteq_motor_controller_driver::config_srv >
template<>
struct DataType< ::roboteq_motor_controller_driver::config_srvResponse>
{
  static const char* value()
  {
    return DataType< ::roboteq_motor_controller_driver::config_srv >::value();
  }
  static const char* value(const ::roboteq_motor_controller_driver::config_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTEQ_MOTOR_CONTROLLER_DRIVER_MESSAGE_CONFIG_SRV_H
