// Generated by gencpp from file roboteq_motor_controller_driver/maintenance_srv.msg
// DO NOT EDIT!


#ifndef ROBOTEQ_MOTOR_CONTROLLER_DRIVER_MESSAGE_MAINTENANCE_SRV_H
#define ROBOTEQ_MOTOR_CONTROLLER_DRIVER_MESSAGE_MAINTENANCE_SRV_H

#include <ros/service_traits.h>


#include <roboteq_motor_controller_driver/maintenance_srvRequest.h>
#include <roboteq_motor_controller_driver/maintenance_srvResponse.h>


namespace roboteq_motor_controller_driver
{

struct maintenance_srv
{

typedef maintenance_srvRequest Request;
typedef maintenance_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct maintenance_srv
} // namespace roboteq_motor_controller_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roboteq_motor_controller_driver::maintenance_srv > {
  static const char* value()
  {
    return "cf026a2baaf512cfffd561e78c18a0ec";
  }

  static const char* value(const ::roboteq_motor_controller_driver::maintenance_srv&) { return value(); }
};

template<>
struct DataType< ::roboteq_motor_controller_driver::maintenance_srv > {
  static const char* value()
  {
    return "roboteq_motor_controller_driver/maintenance_srv";
  }

  static const char* value(const ::roboteq_motor_controller_driver::maintenance_srv&) { return value(); }
};


// service_traits::MD5Sum< ::roboteq_motor_controller_driver::maintenance_srvRequest> should match
// service_traits::MD5Sum< ::roboteq_motor_controller_driver::maintenance_srv >
template<>
struct MD5Sum< ::roboteq_motor_controller_driver::maintenance_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roboteq_motor_controller_driver::maintenance_srv >::value();
  }
  static const char* value(const ::roboteq_motor_controller_driver::maintenance_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roboteq_motor_controller_driver::maintenance_srvRequest> should match
// service_traits::DataType< ::roboteq_motor_controller_driver::maintenance_srv >
template<>
struct DataType< ::roboteq_motor_controller_driver::maintenance_srvRequest>
{
  static const char* value()
  {
    return DataType< ::roboteq_motor_controller_driver::maintenance_srv >::value();
  }
  static const char* value(const ::roboteq_motor_controller_driver::maintenance_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roboteq_motor_controller_driver::maintenance_srvResponse> should match
// service_traits::MD5Sum< ::roboteq_motor_controller_driver::maintenance_srv >
template<>
struct MD5Sum< ::roboteq_motor_controller_driver::maintenance_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roboteq_motor_controller_driver::maintenance_srv >::value();
  }
  static const char* value(const ::roboteq_motor_controller_driver::maintenance_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roboteq_motor_controller_driver::maintenance_srvResponse> should match
// service_traits::DataType< ::roboteq_motor_controller_driver::maintenance_srv >
template<>
struct DataType< ::roboteq_motor_controller_driver::maintenance_srvResponse>
{
  static const char* value()
  {
    return DataType< ::roboteq_motor_controller_driver::maintenance_srv >::value();
  }
  static const char* value(const ::roboteq_motor_controller_driver::maintenance_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTEQ_MOTOR_CONTROLLER_DRIVER_MESSAGE_MAINTENANCE_SRV_H
