// Generated by gencpp from file roboteq_motor_controller_driver/maintenance_srvResponse.msg
// DO NOT EDIT!


#ifndef ROBOTEQ_MOTOR_CONTROLLER_DRIVER_MESSAGE_MAINTENANCE_SRVRESPONSE_H
#define ROBOTEQ_MOTOR_CONTROLLER_DRIVER_MESSAGE_MAINTENANCE_SRVRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roboteq_motor_controller_driver
{
template <class ContainerAllocator>
struct maintenance_srvResponse_
{
  typedef maintenance_srvResponse_<ContainerAllocator> Type;

  maintenance_srvResponse_()
    : result()  {
    }
  maintenance_srvResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::roboteq_motor_controller_driver::maintenance_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboteq_motor_controller_driver::maintenance_srvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct maintenance_srvResponse_

typedef ::roboteq_motor_controller_driver::maintenance_srvResponse_<std::allocator<void> > maintenance_srvResponse;

typedef boost::shared_ptr< ::roboteq_motor_controller_driver::maintenance_srvResponse > maintenance_srvResponsePtr;
typedef boost::shared_ptr< ::roboteq_motor_controller_driver::maintenance_srvResponse const> maintenance_srvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboteq_motor_controller_driver::maintenance_srvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboteq_motor_controller_driver::maintenance_srvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roboteq_motor_controller_driver::maintenance_srvResponse_<ContainerAllocator1> & lhs, const ::roboteq_motor_controller_driver::maintenance_srvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roboteq_motor_controller_driver::maintenance_srvResponse_<ContainerAllocator1> & lhs, const ::roboteq_motor_controller_driver::maintenance_srvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roboteq_motor_controller_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::roboteq_motor_controller_driver::maintenance_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboteq_motor_controller_driver::maintenance_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboteq_motor_controller_driver::maintenance_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboteq_motor_controller_driver::maintenance_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboteq_motor_controller_driver::maintenance_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboteq_motor_controller_driver::maintenance_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboteq_motor_controller_driver::maintenance_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const ::roboteq_motor_controller_driver::maintenance_srvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc22f2a1ed8654a0bULL;
  static const uint64_t static_value2 = 0x365f1bb3f7ff2c0fULL;
};

template<class ContainerAllocator>
struct DataType< ::roboteq_motor_controller_driver::maintenance_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboteq_motor_controller_driver/maintenance_srvResponse";
  }

  static const char* value(const ::roboteq_motor_controller_driver::maintenance_srvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboteq_motor_controller_driver::maintenance_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string result\n"
"\n"
;
  }

  static const char* value(const ::roboteq_motor_controller_driver::maintenance_srvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboteq_motor_controller_driver::maintenance_srvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct maintenance_srvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboteq_motor_controller_driver::maintenance_srvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboteq_motor_controller_driver::maintenance_srvResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTEQ_MOTOR_CONTROLLER_DRIVER_MESSAGE_MAINTENANCE_SRVRESPONSE_H
